[meta] Jump directly to this repo

diff --git a/_zshrc b/_zshrc
--- a/_zshrc
+++ b/_zshrc
@@ -30,7 +30,6 @@ alias it='git'
 alias qgit='git'
 alias gt='git --no-pager'
 alias tmux='tmux -2'
-alias dots='cd ~/.dotfiles'
 alias :e='vim'
 
 if [ -d "$HOME/Notes" ]; then
@@ -46,6 +45,15 @@ fi
 if [ -d "$HOME/Desktop" ]; then
   alias desktop='cd ~/Desktop'
 fi
+
+dots() {
+  dotdir="$(readlink "$HOME/.dotfiles")"
+  if [ ! -d "$dotdir" ]; then
+    echo "ERROR: $dotdir does not exist."
+    exit 1
+  fi
+  cd "$dotdir" || exit 1
+}
 
 xo() { [[ -n "$1" ]] && top -l1 | grep "$1" | cut -d ' ' -f 1 || echo "usage: $0 <process name>" ;  }
 xoxo() { [[ -n "$1" ]] && xo "$1" | xargs kill -9 || echo "usage: $0 <process name>" ; }
